##
##  ci.yml
## 

name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-macOS:
    name: Build
    runs-on: macos-12
    
    steps:
      - uses: actions/checkout@v3
      - name: Test build
        run: echo "tested build nicely"
